variables:
  CONTAINER_REGISTRY_HOST: docker.io
  CONTAINER_PROJECT_PATH: /miracum/uc1-registry-multisitemerger

include:
  - project: "devops/ci-templates"
    file: "/standard/.container-build.yml"

.registry_login:
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME $CONTAINER_REGISTRY_HOST --password-stdin
  after_script:
    - docker logout $CONTAINER_REGISTRY_HOST

e2e:
  extends:
    - .job_defaults
  stage: test
  image:
    name: docker/compose:1.26.2
    entrypoint: [""]
  before_script:
    - mkdir -p /cache/$CI_PROJECT_NAME
    - cp -r deploy/studies.dev.json /cache/$CI_PROJECT_NAME/
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - export E2E_TEST_DATA_FILE_PATH=/cache/$CI_PROJECT_NAME/studies.dev.json
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml build
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml run loader
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml run tester
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID-e2e -f tests/e2e/docker-compose.yml down --volumes --remove-orphans
