apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: trials-registry
  app.kubernetes.io/managed-by: kustomize
resources:
  - web-deployment.yaml
  - web-service.yaml
  - merger-deployment.yaml
  - merger-service.yaml
helmCharts:
  - name: hapi-fhir-jpaserver
    repo: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.11.0
    valuesInline:
      postgresql:
        auth:
          postgresPassword: hapi-fhir-postgres-admin-pass
