apiVersion: v1
kind: Service
metadata:
  name: multi-site-merger
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: multi-site-merger
