apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-site-merger
  labels:
    app.kubernetes.io/name: multi-site-merger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-site-merger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-site-merger
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: multi-site-merger
          image: ghcr.io/miracum/registry-on-fhir/multi-site-merger:2.1.9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: "FHIR_URL"
              value: "http://registry-fhir-server-hapi-fhir-jpaserver:8080/fhir"
            - name: "WEBHOOK_ENDPOINT"
              value: "http://multi-site-merger:8080/updates"
            - name: "MERGE_SCHEDULE"
              value: "0 0 1 * * *"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            privileged: false
            runAsGroup: 65532
            runAsUser: 65532
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1024Mi
              cpu: 250m
