workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

variables:
  CONTAINER_REGISTRY_HOST: docker.io

include:
  - project: "devops/ci-templates"
    file: "/preflight/.tidy-files.yml"

  - project: "devops/ci-templates"
    file: "/linting/.yamllint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.markdownlint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.hadolint.yml"

  - project: "devops/ci-templates"
    file: "/versioning/.semantic-release-get-version.yml"

  - project: "devops/ci-templates"
    file: "/release/.gitlab-release.yml"

stages:
  - preflight
  - lint
  - version
  - triggers
  - release
  - deploy

hadolint:
  script:
    - hadolint web/Dockerfile
    - hadolint multisitemerger/Dockerfile

web:
  stage: triggers
  needs: ["get next version"]
  trigger:
    include: web/.gitlab-ci.yml
    strategy: depend

multisitemerger:
  stage: triggers
  needs: ["get next version"]
  trigger:
    include: multisitemerger/.gitlab-ci.yml
    strategy: depend

staging:
  stage: deploy
  needs:
    - web
    - multisitemerger
  image:
    name: quay.io/chgl/kube-powertools:latest
    entrypoint: [""]
  environment:
    name: staging
  script:
    - helm repo add chgl https://chgl.github.io/charts
    - helm repo update
    - helm upgrade --version 0.2.0 --install -n $KUBE_NAMESPACE -f deploy/helm/fhir-server-staging.yaml fhir-server chgl/hapi-fhir-jpaserver
    - cd deploy/kustomize/overlays/staging
    - kustomize edit set image docker.io/miracum/uc1-registry-web=docker.io/miracum/uc1-registry-web:$CI_COMMIT_SHORT_SHA
    - kustomize edit set image docker.io/miracum/uc1-registry-multisitemerger=docker.io/miracum/uc1-registry-multisitemerger:$CI_COMMIT_SHORT_SHA
    - kustomize build | kubectl apply -n $KUBE_NAMESPACE -f -
  when: manual

production:
  stage: deploy
  image:
    name: quay.io/chgl/kube-powertools:latest
    entrypoint: [""]
  environment:
    name: production
  script:
    - helm repo add chgl https://chgl.github.io/charts
    - helm repo update
    - helm upgrade --version 0.2.0 --install -n $KUBE_NAMESPACE -f deploy/helm/fhir-server-production.yaml fhir-server chgl/hapi-fhir-jpaserver
    - cd deploy/kustomize/overlays/production
    - kustomize edit set image docker.io/miracum/uc1-registry-web=docker.io/miracum/uc1-registry-web:$CI_COMMIT_TAG
    - kustomize edit set image docker.io/miracum/uc1-registry-multisitemerger=docker.io/miracum/uc1-registry-multisitemerger:$CI_COMMIT_TAG
    - kustomize build | kubectl apply -n $KUBE_NAMESPACE -f -
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
