# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - JAVASCRIPT_STANDARD
  - JAVA_PMD
  # due to import-error
  - PYTHON_PYRIGHT
  # due to import-error
  - PYTHON_PYLINT
  - REPOSITORY_CHECKOV
  # false positive for requirements.txt --hash option
  - REPOSITORY_DUSTILOCK

JAVA_CHECKSTYLE_CONFIG_FILE: multi-site-merger/.checkstyle/checkstyle.xml

GROOVY_NPM_GROOVY_LINT_ARGUMENTS:
  - "--failon=warning"

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity='HIGH,CRITICAL'"
