apiVersion: skaffold/v3
kind: Config
metadata:
  name: registry-on-fhir
build:
  local:
    concurrency: 2
    tryImportMissing: false
    useDockerCLI: false
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/miracum/registry-on-fhir/multi-site-merger
      context: multi-site-merger
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/miracum/registry-on-fhir/web
      context: web
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: hapi-fhir-jpaserver
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: true
        repo: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
        remoteChart: hapi-fhir-jpaserver
        version: 0.11.0
        # TODO: figure out why this doesn't work despite https://github.com/GoogleContainerTools/skaffold/pull/8011
        # skipTests: true
        setValues:
          postgresql.auth.postgresPassword: hapi-fhir-postgres-admin-pass
  kustomize:
    paths:
      - k8s\kustomize\base
profiles:
  - name: prod
    manifests:
      kustomize:
        paths:
          - k8s\kustomize\overlays\prod
  - name: staging
    manifests:
      kustomize:
        paths:
          - k8s\kustomize\overlays\staging
