apiVersion: skaffold/v3
kind: Config
metadata:
  name: registry-on-fhir
build:
  local:
    concurrency: 2
    tryImportMissing: false
    useDockerCLI: false
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/miracum/registry-on-fhir/multi-site-merger
      context: multi-site-merger
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/miracum/registry-on-fhir/web
      context: web
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s\kustomize\base
profiles:
  - name: prod
    manifests:
      kustomize:
        paths:
          - k8s\kustomize\overlays\prod
  - name: staging
    manifests:
      kustomize:
        paths:
          - k8s\kustomize\overlays\staging
