apiVersion: apps/v1
kind: Deployment
metadata:
  name: multisitemerger
  labels:
    app.kubernetes.io/name: multisitemerger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: multisitemerger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multisitemerger
    spec:
      automountServiceAccountToken: false
      containers:
        - name: multisitemerger
          image: miracum/uc1-registry-multisitemerger:1.4.11
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: "FHIR_URL"
              value: "http://hapi-fhir-server:8080/fhir"
            - name: "WEBHOOK_ENDPOINT"
              value: "http://multisitemerger:8080/updates"
            - name: "MERGE_SCHEDULE"
              value: "0 0 1 * * *"
          securityContext:
            allowPrivilegeEscalation: false
