version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:8.1.3
    restart: always
    ports:
      - "8082:8080"
    environment:
      server.address: http://localhost:8082/fhir

  loader:
    image: curlimages/curl:7.75.0
    command: >
      -X POST
      -H "Content-Type: application/json"
      --retry-connrefuse
      --connect-timeout 10
      --max-time 60
      --retry 5
      --retry-delay 10
      --data "@/studies.fhirbundle.json"
      http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./studies.fhirbundle.json:/studies.fhirbundle.json:ro
