apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - registry-on-fhir-image-policy.yaml
  - bitnami-image-policy.yaml
images:
  - name: ghcr.io/miracum/registry-on-fhir/multi-site-merger
    newTag: master
  - name: ghcr.io/miracum/registry-on-fhir/web
    newTag: master
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: multi-site-merger
    spec:
      template:
        spec:
          containers:
            - name: multi-site-merger
              imagePullPolicy: Always
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web
    spec:
      template:
        spec:
          containers:
            - name: web
              imagePullPolicy: Always
helmCharts:
  - name: hapi-fhir-jpaserver
    repo: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.11.0
    namespace: registry
    valuesInline:
      postgresql:
        auth:
          postgresPassword: hapi-fhir-postgres-admin-pass
