name: build

on:
  push:
    branches: [master]
  release:
    types: [created]
  pull_request:
    branches: [master]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        component:
          - web
          - multi-site-merger
    outputs:
      image-tags: ${{ steps.container_meta.outputs.tags }}
      image-version: ${{ steps.container_meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Container meta for image
        id: container_meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.component }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # can't use `load` and `push` at the same time, so differentiate by whether its a PR or not
      - name: Build and push image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3
        with:
          load: ${{ github.event_name == 'pull_request' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.container_meta.outputs.tags }}
          labels: ${{ steps.container_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.component }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe # tag=v0.7.1
        with:
          image-ref: ${{ fromJson(steps.container_meta.outputs.json).tags[0] }}
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: "true"

      - name: Save container image as tar archives
        if: ${{ github.event_name == 'pull_request' }}
        env:
          IMAGE: ${{ fromJson(steps.container_meta.outputs.json).tags[0] }}
        run: |
          docker save "$IMAGE" -o /tmp/${{ matrix.component }}-image.tar

      - name: Upload container image
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
        with:
          name: ${{ matrix.component }}-image-artifacts
          path: |
            /tmp/${{ matrix.component }}-image.tar

  test-multisite-merger:
    name: test multi site merger
    runs-on: ubuntu-22.04
    needs:
      - build
    env:
      COMPONENT_NAME: multi-site-merger
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Container meta for image
        id: container_meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.COMPONENT_NAME }}

      - name: Download image
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: ${{ env.COMPONENT_NAME }}-image-artifacts
          path: /tmp

      - name: Load image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ls -lar /tmp
          docker load --input /tmp/${{ env.COMPONENT_NAME }}-image.tar
          docker image ls -a

      - name: Start compose deployment
        working-directory: ${{ env.COMPONENT_NAME }}
        env:
          IMAGE_TAG: ${{ steps.container_meta.outputs.version }}
        run: |
          echo "Using image tag ${IMAGE_TAG}"

          docker compose -f tests/e2e/docker-compose.yaml build

          docker compose -f tests/e2e/docker-compose.yaml run loader
          docker compose -f tests/e2e/docker-compose.yaml run tester

      - name: Print compose logs
        working-directory: ${{ env.COMPONENT_NAME }}
        if: always()
        run: |
          docker compose -f tests/e2e/docker-compose.yaml logs
          docker compose -f tests/e2e/docker-compose.yaml down --volumes --remove-orphans

  test-web:
    name: test web
    runs-on: ubuntu-22.04
    needs:
      - build
    env:
      COMPONENT_NAME: web
    if: ${{ false }}
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          fetch-depth: 0

      - name: Container meta for image
        id: container_meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.COMPONENT_NAME }}

      - name: Download image
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: ${{ env.COMPONENT_NAME }}-image-artifacts
          path: /tmp

      - name: Load image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ls -lar /tmp
          docker load --input /tmp/${{ env.COMPONENT_NAME }}-image.tar
          docker image ls -a

      - name: Start compose deployment
        working-directory: ${{ env.COMPONENT_NAME }}/frontend
        env:
          IMAGE_TAG: ${{ steps.container_meta.outputs.version }}
        run: |
          echo "Using image tag ${IMAGE_TAG}"

          docker compose -f tests/e2e/docker-compose.yaml build

          docker compose -f tests/e2e/docker-compose.yaml run loader
          docker compose -f tests/e2e/docker-compose.yaml run tester

      - name: Print compose logs
        working-directory: ${{ env.COMPONENT_NAME }}/frontend
        if: always()
        run: |
          docker compose -f tests/e2e/docker-compose.yaml logs
          docker compose -f tests/e2e/docker-compose.yaml down --volumes --remove-orphans

  sign-images:
    name: sign images
    runs-on: ubuntu-22.04
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - build
      - test-web
      - test-multisite-merger
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container meta for images
        id: container_meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/web
            ghcr.io/${{ github.repository }}/multi-site-merger

      - name: Install Cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # tag=v2.8.1

      - name: Sign images
        env:
          COSIGN_EXPERIMENTAL: "true"
          IMAGES: ${{ steps.container_meta.outputs.version }}
        run: |
          while read -r image; do
            echo "Signing '$image' using keyless approach"
            cosign sign "$image"
          done <<< "$IMAGES"
