name: release-please

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  release-please:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@2a4590f9c1d322790253d997de5cad7f7ad4bc1b # tag=v3.5.1
        with:
          token: ${{ secrets.MIRACUM_BOT_SEMANTIC_RELEASE_TOKEN }}
          release-type: simple
          extra-files: |
            k8s/kustomize/base/merger-deployment.yaml
            k8s/kustomize/base/web-deployment.yaml
            web/Dockerfile
            multi-site-merger/build.gradle
          changelog-types: |
            [
              { "type": "feat", "section": "Features" },
              { "type": "fix", "section": "Bug Fixes" },
              { "type": "perf", "section": "Performance Improvements" },
              { "type": "docs", "section": "Documentation", "hidden": false },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": false
              },
              { "type": "build", "section": "Build", "hidden": false },
              { "type": "ci", "section": "CI/CD", "hidden": false }
            ]
