# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: scheduled trivy scan

on:
  schedule:
    - cron: "16 17 * * 2"

permissions:
  contents: read

jobs:
  scan-image:
    name: scan
    runs-on: "ubuntu-22.04"
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    strategy:
      matrix:
        component:
          - web
          - multi-site-merger
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ghcr.io/${{ github.repository }}/${{ matrix.component }}:latest
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results-${{ matrix.component }}.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@f0a12816612c7306b485a22cb164feb43c6df818 # tag=v2.1.29
        with:
          sarif_file: "trivy-results-${{ matrix.component }}.sarif"
