workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

variables:
  CONTAINER_PROJECT_PATH: "/miracum/uc1-registry-web"
  IMAGE_PATH: $CONTAINER_REGISTRY_HOST$CONTAINER_PROJECT_PATH

.registry_login:
  before_script:
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME $CONTAINER_REGISTRY_HOST --password-stdin
  after_script:
    - docker logout $CONTAINER_REGISTRY_HOST

include:
  - project: "devops/ci-templates"
    file: "/versioning/.semantic-release-get-version.yml"
  - project: "devops/ci-templates"
    file: "/image-scanning/.trivy-scan.yml"
  - project: "devops/ci-templates"
    file: "/release/.push-to-registry.yml"

stages:
  - version
  - build
  - test
  - release

container:
  stage: build
  extends: .registry_login
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
  script:
    - cd web/
    - export VERSION=$(cat .VERSION)
    - docker build -t $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
      --build-arg VERSION=$VERSION
      --build-arg GIT_REF=$CI_COMMIT_SHA
      --build-arg BUILD_TIME="$(date -Is)" .
    - docker push $IMAGE_PATH:$CI_COMMIT_SHORT_SHA

unit:
  stage: test
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
  script:
    - cd web/
    - docker build -f tests/unit/Dockerfile .
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

trivy:
  variables:
    IMAGE_FQN: $CONTAINER_REGISTRY_HOST$CONTAINER_PROJECT_PATH:$CI_COMMIT_SHORT_SHA

e2e:
  image:
    name: docker/compose:1.26.2
    entrypoint: [""]
  stage: test
  script:
    # ideally, we should instead allow for mounting the build directory directly.
    - cd web/
    - export E2E_PATH=/cache/uc1/registry/web/$CI_JOB_ID
    - mkdir -p $E2E_PATH
    - cp -r tests/ $E2E_PATH
    - cp cypress.json $E2E_PATH
    - cp -r deploy/ $E2E_PATH
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run loader
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml run e2e
  after_script:
    - cd web/
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.e2e.yml down --remove-orphans
    - rm -rf /cache/uc1/registry/web/$CI_JOB_ID
