services:
  fhir:
    image: docker.io/hapiproject/hapi:v6.8.0@sha256:b376ef983c54757aff719b17e97301eab43198564d23f2aa9609e9b5f83fa85f
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
      HAPI_FHIR_NARRATIVE_ENABLED: "false"
    ports:
      - 127.0.0.1:8082:8080

  loader:
    image: docker.io/curlimages/curl:7.88.1@sha256:48318407b8d98e8c7d5bd4741c88e8e1a5442de660b47f63ba656e5c910bc3da
    command: >
      -X POST -H "Content-Type: application/fhir+json" --retry-connrefuse --connect-timeout 10 --max-time 60 --retry 5 --retry-delay 10 --data "@/studies.fhirbundle.json" http://fhir:8080/fhir
    depends_on:
      - fhir
    volumes:
      - ./frontend/tests/e2e/studies.fhirbundle.json:/studies.fhirbundle.json:ro
